### ISSUE TITLE
Add `dev` scripts to `package.json` in Tutor supported MFEs

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/frontend-wg#183]
MFE development outside of docker with Tutor is possible (and documented as of https://github.com/openedx/frontend-app-learning/pull/1472).

We should update all Tutor supported MFEs so `npm run dev` works for local development with Tutor!

```[tasklist]
### Tasks
- [ ] [Authn](https://github.com/openedx/frontend-app-authn/)
- [x] [Authoring](https://github.com/openedx/frontend-app-authoring/) https://github.com/openedx/frontend-app-authoring/pull/1364
- [ ] [Discussions](https://github.com/openedx/frontend-app-discussions/)
- [ ] [Account](https://github.com/openedx/frontend-app-account/)
- [ ] [Communications](https://github.com/openedx/frontend-app-communications/)
- [ ] [Gradebook](https://github.com/openedx/frontend-app-gradebook/)
- [x] [Learner Dashboard](https://github.com/openedx/frontend-app-learner-dashboard/) https://github.com/openedx/frontend-app-learner-dashboard/pull/530
- [x] [Learning](https://github.com/openedx/frontend-app-learning/) https://github.com/openedx/frontend-app-learning/pull/1472
- [ ] [ORA Grading](https://github.com/openedx/frontend-app-ora-grading/)
- [ ] [Profile](https://github.com/openedx/frontend-app-profile/)
```

**Comment by regisb** [comment]
I suggest we primarily update the instructions in tutor-mfe, and then link to the instructions from every MFE. Note that the proposed `tutor dev start lms cms mfe` command will work only partially, as it will not start other services, such as notes, aspects, etc.

**Comment by arbrandes** [comment]
I'm pretty sure this is done.
